### ISSUE TITLE
store dbSNP VCF 

### ISSUE THREAD

**Issue by darked89** [TileDB-Inc/TileDB-VCF#344]
Hello,

I am trying to store the dbSNP ver 155 VCF file obtained using this link:

https://ftp.ncbi.nih.gov/snp/latest_release/VCF/GCF_000001405.39.gz

the problem:

I am getting addres boundary errors while running:

```
singularity exec --no-home --bind ./data:/data tiledbvcf-cli_latest.sif tiledbvcf store --uri /data/tiledb_dbSNP_155_hg38 /data/dbSNP_155.GRCh38.names_fixed.vcf.gz
```

Same with the original GCF_000001405.39.gz. Both indexed with bcftools with --csi
Storing/ingesting another VCF works: Good VCF format:
```
#contig=<ID=GL000192.1,length=547496,assembly=GRCh37>
##Gwas2VCF_command=--data /data/example.1k.txt --json /data/params.repo_example.json --id example.1kxxx --ref /data/human_g1k_v37.fasta --dbsnp /data/dbsnp.v153.b37.vcf.gz --out
 /data/example.1k.out.vcf --alias /app/alias.txt; 1.3.1
##file_date=2021-06-28T11:57:57.764058
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  example.1kxxx
10      1011166 rs11253538      C       T       .       PASS    AF=0.1939       ES:SE:LP:AF:SS:ID       0.0055:0.0067:0.168578:0.1939:89888:rs11253538
10      1011347 rs11253539      G       A       .       PASS    AF=0.1939       ES:SE:LP:AF:SS:ID       0.0045:0.0067:0.105518:0.1939:89888:rs11253539
1
```

dbSNP bad format:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
NC_000001.11    10001   rs1570391677    T       A,C     .       .       RS=1570391677;dbSNPBuildID=154;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=KOREAN:0.9891,0.
0109,.|SGDP_PRJ:0,1,.|dbGaP_PopFreq:1,.,0;COMMON
NC_000001.11    10002   rs1570391692    A       C       .       .       RS=1570391692;dbSNPBuildID=154;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=KOREAN:0.9944,0.
005597
NC_000001.11    10003   rs1570391694    A       C       .       .       RS=1570391694;dbSNPBuildID=154;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=KOREAN:0.9902,0.
009763
```

In short: is thr dbSNP VCF format  not yet supported?

**Comment by aaronwolen** [comment]
Thanks for posting, @darked89. We're looking into this and will report back shortly.

**Comment by aaronwolen** [comment]
Hey @darked89, we had a chance to look over the file you referenced and spotted a couple of issues that make it incompatible with TileDB-VCF, the most problematic of which is the lack of a sample column.

We can definitely look into adding support for ingesting VCFs without sample info but could you give us a little more information about your use case, and/or how often you use sample-less files like this in your work?

**Comment by darked89** [comment]
Dear Aaron,

Thank you for looking into this.

in short: the VCF file in question is central to a lot of mutation and GWAS analyses. No idea of the bat if there are any other VCF files with format like this, but then it is a very special and important resource (see below). 

As the name implies it is a database of SNPs maintained by NCBI , something one should compare the variants found in properly formatted VCFs, like outputs of i e. GATK package, genotyping etc. The publication describing it (https://doi.org/10.1093/nar/29.1.308)  has over 6200 scientific citations (Google Scholar) so far.  
It is used to be queried using positions from run of the mill sample VCFs .  

I think there are may be two ways to address the problem TileDB vs dbSNP VCF format:

1. Modify the TileDB-VCF so it can handle such case (VCF withouth the sample name)
2. Modify the offending dbSNP file so it will be compatible with TileDB-VCF.

Ad 2:
If you point me to a description of TileDB-VCF's minimal set of required VCF fields I will try to figure out if this approach makes sense.

**Comment by aaronwolen** [comment]
Apologies for the slow response, @darked89. I've been looking into this and have some more info for you.

But to answer your above question, TileDB-VCF stores data using a 3-dimensional schema indexed by sample name, contig, and start position, so we currently look for sample names in VCF files immediately after starting an ingest.

Apart from the dimensions, the schema expects the following attributes:

```c
std::set<std::string> TileDBVCFDataset::builtin_attributes_v4() {
  return {
      AttrNames::V4::real_start_pos,
      AttrNames::V4::end_pos,
      AttrNames::V4::qual,
      AttrNames::V4::alleles,
      AttrNames::V4::id,
      AttrNames::V4::filter_ids,
      AttrNames::V4::info,
      AttrNames::V4::fmt};
}
```

So, as discussed, ingesting VCFs missing `FORMAT`/sample columns will fail. However, this is clearly a great use case for TileDB-VCF and we're going to looking into making the necessary modifications to properly support it. 

In the meantime, you can workaround the current limitations by adding a dummy sample to your VCF. I was able to get this approach working with a VCF file downloaded from ClinVar, which is formatted very similarly to dbGap's but is quite a bit smaller, making it easier to experiment with.  To get it ingested I had to make the following modifications:

 - used `bcftools reheader` to add lengths to the defined contigs
-  added `##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">` to the header to define a `FORMAT/GT` field
- added dummy genotypes to every variant, i.e., 

    ```
    FORMAT	sample1
    GT	./.
    ```

After that I was able to ingest and query using TileDB-VCF without issue. I wrapped up this process in a `Makefile` you can access [here](https://gist.github.com/aaronwolen/80307425a2f98ff6207b8165d633e49a).  

Let me know if that works for you in the short term and we'll follow-up re adding proper support for annotation VCFs.

**Comment by darked89** [comment]
Hello,

I have followed your instructions with some twists:

1. last line of the new VCF header as in the linked by you make file needs to be:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1
```

2. because uncompressed dbSNP VCF can easily run in +100GB I have used bgzip and some bash hacks to get a valid and indexable bgzip-ed VCF:

```
#!/usr/bin/bash

(cat dbSNP155_1-22xy.only.vcf.header.new; bcftools view --no-header dbSNP155_1-22xy.only.vcf.gz | head -100000 | awk 'BEGIN{OFS="\t"}{print $0, "GT", "./."}' ) | b
gzip > test_tiledbvcf_dbsnp.vcf.gz
```

At the moment I got a tiny test file (see head -100000) but the full blow run with more useful result is ongoing.
I will keep you posted when it will be done.

Darek Kedra

**Comment by Imoteph** [comment]
@aaronwolen any update, is this now possible out of the box, or is still the mocking of a "fake" sample necessary?

**Comment by gspowley** [comment]
@Imoteph, there are changes in development that will make this possible out of the box. The changes should be available in a release next week.

**Comment by gspowley** [comment]
Please try release [0.23.1](https://github.com/TileDB-Inc/TileDB-VCF/releases/tag/0.23.1).

**Comment by gspowley** [comment]
Closing this issue since it has been inactive. Please reopen if there is still an issue.
