### ISSUE TITLE
locale::facet::_S_create_c_locale name not valid (ver 0.11.1)

### ISSUE THREAD

**Issue by darked89** [TileDB-Inc/TileDB-VCF#376]
Hello,

I am getting the error in the issue subject while executing:

```
 singularity exec --bind ../release_7:/data  ~/SIFs/tiledbvcf-cli_0.11.1.sif tiledbvcf store --uri /data/R7_tiledbvcf /data/02_tsv2vcf_results/finngen_R7_AB1_AMOEBIASIS.gwas2vcf.annot.vcf.gz
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
fish: Job 1, 'singularity exec --bind ../rele…' terminated by signal SIGABRT (Abort)
```

To get the above Singularity image and initiate the TileDB database I did:
```
#get the image
singularity pull tiledbvcf-cli_0.11.1.sif  docker://tiledb/tiledbvcf-cli:0.11.1

#create the store/initiate db
singularity exec --bind ../release_7:/data  ~/SIFs/tiledbvcf-cli_0.11.1.sif tiledbvcf create --uri /data/R7_tiledbvcf
``` 

The commands work just fine with version obtained from:  docker://tiledb/tiledbvcf-cli:0.9.0

On the positive side: 
```tiledbvcf extract``` took just 2.5mins to dump +700k rows doing a query on a fairly large 3k VCFs +16M variants each/1.9TB  using not exactly optimal NFS-mounted storage. Very impressive!

Thank you for your help

Darek Kedra

**Comment by darked89** [comment]
This was trivial to solve:

```
export LC_ALL=C; unset LANGUAGE
```

Despite that it was crying wolf hopefully it may be useful for others.

Closing as it is resolved

DK

**Comment by gspowley** [comment]
@darked89 , Thank you for sharing the issue and resolution. Glad you are seeing impressive performance on your project!
