### ISSUE TITLE
TileDB-VCF's docs missing

### ISSUE THREAD

**Issue by aardes** [TileDB-Inc/TileDB-VCF#385]
Dear,

Could you please let me know would it be possible to check the TileDB-VCF's docs ? 

URL is not valid anymore: https://docs.tiledb.com/main/solutions/integrations/population-genomics

thanks in advance
Regards

**Comment by gspowley** [comment]
Thanks for pointing out the broken link. 

The new location is: https://docs.tiledb.com/main/integrations-and-extensions/population-genomics

We'll update the links in README.md.
