### ISSUE TITLE
coordinates

### ISSUE THREAD

**Issue by stevemmarshall** [TileDB-Inc/TileDB-VCF#40]
Hi

I tried to load some example BCFs... and got this message. Does ingestion requires a sorted file?

tiledbvcf store --uri my-dataset *C*_SNP_INDEL_recal.vcf.bcf
[2019-11-14 22:25:28.049] [tiledb] [Process: 550] [Thread: 684] [error] [TileDB::Writer] Error: Write failed; Coordinates (5,6233885) succeed (5,6233870) in the global order
terminate called after throwing an instance of 'tiledb::TileDBError'
  what():  [TileDB::Writer] Error: Write failed; Coordinates (5,6233885) succeed (5,6233870) in the global order

Thanks
Steve

**Comment by tdenniston** [comment]
Hi @stevemmarshall,

Yes, you are correct that ingestion requires sorted files. There are a few other limitations (such as no overlapping records within a sample), documented in the "Advanced" section of the docs here: https://docs.tiledb.com/developer/tiledbvcf/advanced/ingestion-algorithm#limitations

**Comment by nuin** [comment]
I know this is an old issue, but I had the same problem while ingesting some sorted indexed VCFs (double checked). The solution was to ingest each file separately in a bash loop and isolate the one with the issue. I tried grepping/visually checking (it's a small file) for the coordinates in the error and the values do not appear in the file.

**Comment by gspowley** [comment]
Closing this issue since it has been inactive. Please reopen if there is still an issue.
