### ISSUE TITLE
tiledbvcf extract --merge 

### ISSUE THREAD

**Issue by gpertea** [TileDB-Inc/TileDB-VCF#427]
An important use case for me is using `tiledbvcf extract` to export a single cVCF with a subset of samples of interest for downstream analyses (e.g. eQTL) . I see that I needed to specifically use option `-m` with `export` for that, otherwise the default output is a a vcf/bcf file for each sample (which does not seem very useful for me, but I am obviously biased towards cVCFs)

The problem is that tiledbvcf does not seem to support the `-m` option in version v2.6.4 which is the current conda version at this time. Strangely enough it was present in an older version v2.6.3 so I tried it with that version and it did not go well.

After ingesting ~2400 samples (for ~6million SNPs) I wanted to test the performance of extracting a subset of samples (all SNPs, not a region subset) as a cVCF. This worked pretty well for 2 sample IDs passed to `tiledbvcf extract -m -s` option (much faster than bcftools, which is what I am comparing it to, since bcftools has to scan the whole cVCF to do the same), but failed when I tried `tiledbvcf extract -m -f` with a list of 280 randomly picked samples: the process ran for days with no end in sight, so I had to kill it (bcftools did that in about 16 minutes, I just hoped tiledbcvf would be able to do the same but faster) 

Considering this extraction feature (the `-m, --merge` option) is no longer present in the most recent conda version, are there any plans to bring it back (and fix it)?

**Comment by gspowley** [comment]
Thanks @gpertea for sharing your experience with the combined VCF export. It looks like you caught a WIP release of combined VCF export in conda. We just released TileDB-VCF 0.14.0, which has the combined VCF export feature enabled (it will take some time from this comment post to propagate to conda).

Can you please run the `tiledbvcf export` command with the `--log-level debug` option and share the log messages? Log messages from ~10-15 minutes should be enough to start investigating the performance.

**Comment by gspowley** [comment]
Closing this issue since it has been inactive. Please reopen if there is still an issue.
