### ISSUE TITLE
How to delete a sample from the database?

### ISSUE THREAD

**Issue by ghost** [TileDB-Inc/TileDB-VCF#443]

**Comment by 1pakch** [comment]
I'm curious as well. Removal of a sample is quite a relevant scenario (for instance, when the consent is withdrawn or some kind of upstream processing error is detected).

The [official API docs](https://docs.tiledb.com/main/integrations-and-extensions/genomics/population-genomics/api-reference/python) don't seem to mention deletion but I guess it is likely possible with the [lower-level interface](https://docs.tiledb.com/main/how-to/arrays/writing-arrays/deleting).

**Comment by gspowley** [comment]
Sample deletion is supported [by the CLI](https://tiledb-inc.github.io/TileDB-VCF/documentation/api-reference/cli.html#delete). 

For example:
```
tiledbvcf delete -u VCF_DATASET_URI -s SAMPLE_NAME
```

**Note** - TileDB-VCF API docs are in the process of moving to [GitHub pages](https://tiledb-inc.github.io/TileDB-VCF/documentation/index.html).
