### ISSUE TITLE
Different behaviour using regions or regions-file and maybe two bugs

### ISSUE THREAD

**Issue by cristianrohr** [TileDB-Inc/TileDB-VCF#449]
Hello!

I noticed a differente behaviour betweens the --regions and the --regions-file parameter

A query using --regions works "almost" as expected

./tiledbvcf export --uri rewelldb --regions "7:150553605-150553605" -Ot --tsv-fields "CHR,POS,REF,S:GT"

This returns the information for this position on the DB, but the DB have 9 samples, and the results return 12 records, 3 records are duplicated

./tiledbvcf export --uri XXX --regions "7:150553605-150553605" -Ot --tsv-fields "CHR,POS,REF,S:GT" | sort | uniq -c
      1 X000305-S	7	150553605	C	0,0
      2 X000610-S	7	150553605	C	0,0
      1 X001008-S	7	150553605	C	0,0
      2 X004903-S	7	150553605	C	0,0
      2 X005007-S	7	150553605	C	0,0
      1 X005105-S	7	150553605	C	0,0
      1 X005301-S	7	150553605	C	0,0
      1 X005508-S	7	150553605	C	0,1
      1 X005606-S	7	150553605	C	0,1
      1 SAMPLE	CHR	POS	REF	S:GT
      
If i use the same region inside a .bed file, with the --regions-file parameter the cli starts to print the whole db instead of only the information on the position

thanks!

**Comment by aaronwolen** [comment]
Hi @cristianrohr, thanks for reporting. If it isn't too large, could you share the bedfile with us to examine as well as the export command you performed? That will help us attempt to reproduce on our end.

**Comment by gspowley** [comment]
Closing this issue since it has been inactive. Please reopen if there is still an issue.
