### ISSUE TITLE
invalid next size  on export -m gatk gvcfs

### ISSUE THREAD

**Issue by Imoteph** [TileDB-Inc/TileDB-VCF#515]
Hi,

I am testing a bit how tiledb-vcf is maybe able to store as well gvcfs from gatk pipeline and I stumbled on this issue where I am getting an invalid next size error message when I try to get vcf exported which has been stored in the tiledb-vcf db. Any hint of what it actually means?
I only loaded 2 samples into it. 

Here the debug message:

```bash
[tiledb-vcf] [Process: 1] [Thread: 1] [info] Initialized TileDB query with 1 start_pos ranges, all samples for contig 1 (contig batch 1/194, sample batch 1/0).
 [tiledb-vcf] [Process: 1] [Thread: 1] [info] TileDB query started. (VmRSS = 0.285 GiB)
 [tiledb-vcf] [Process: 1] [Thread: 1] [info] TileDB query completed in 10.081 sec. (VmRSS = 2.401 GiB)
realloc(): invalid next size
```

**Comment by gspowley** [comment]
Thanks @Imoteph, this looks like an issue we have seen before in combined VCF export. Which version of TileDB-VCF were you using? If it's possible for you to share the VCF files, we can reproduce and debug further.

**Comment by Imoteph** [comment]
any potential hint, on how I could maybe debug this error?

**Comment by gspowley** [comment]
Thanks for the offer. We've reproduced the error and are working on a fix.

**Comment by gspowley** [comment]
Please try release [0.23.1](https://github.com/TileDB-Inc/TileDB-VCF/releases/tag/0.23.1).

**Comment by Imoteph** [comment]
Thx, I will close this issue for now.
