### ISSUE TITLE
Exporting VCF writes "binary" DB INFO field

### ISSUE THREAD

**Issue by michaeljon** [TileDB-Inc/TileDB-VCF#542]
Exporting BCF to VCF format writes a `DB` INFO field that contains non-ASCII characters. For example `DB=<B8>^^žDP`.

```
NC_000014.9	94378225	rs2073333	C	T	64.64	.	AC=1;AF=0.5;AN=2;BaseQRankSum=-0.589;DB=���DP;DP=9;ExcessHet=0;FS=0;MLEAC=1;MLEAF=0.5;MQ=43.96;MQRankSum=-2.655;QD=7.18;ReadPosRankSum=1.309;SOR=0.446	GT:AD:DP:GQ:PL	0/1:5,4:9:72:72,0,107
```

which looks like 

```
00000040  51 52 61 6e 6b 53 75 6d  3d 2d 30 2e 35 38 39 3b  |QRankSum=-0.589;|
00000050  44 42 3d b4 c8 16 bf 44  50 3b 44 50 3d 39 3b 45  |DB=....DP;DP=9;E|
00000060  78 63 65 73 73 48 65 74  3d 30 3b 46 53 3d 30 3b  |xcessHet=0;FS=0;|
```

**Comment by michaeljon** [comment]
More info that I should have added initially. This is built-from-source, not installed. The DB INFO is a flag

```
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP Membership">
```

It shows up in the source records as 

```
NC_000014.9	94378225	rs2073333	C	T	64.64	.	AC=1;AF=0.500;AN=2;BaseQRankSum=-0.589;DB;DP=9;ExcessHet=0.0000;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=43.96;MQRankSum=-2.655;QD=7.18;ReadPosRankSum=1.309;SOR=0.446	GT:AD:DP:GQ:PL	0/1:5,4:9:72:72,0,107```

**Comment by awenocur** [comment]
Hi @michaeljon , this is a known limitation with how we handle INFO fields of type Flag. We are developing an update to handle this type properly.

**Comment by michaeljon** [comment]
Thanks for the update, I'll keep an eye open.

**Comment by awenocur** [comment]
There is a fix for this defect when exporting to VCF, in #543.

**Comment by gspowley** [comment]
Closing this issue since it has been inactive. Please reopen if there is still an issue.
