### ISSUE TITLE
Azure blob storage credential parsing problem

### ISSUE THREAD

**Issue by vstathias** [TileDB-Inc/TileDB-VCF#603]
Error when using the credentials to connect to an azure blob
``` 
azure_cred = ["vfs.azure.storage_account_name=myblob", "vfs.azure.storage_sas_token=?sv=123456789=="]
config = tiledbvcf.ReadConfig(tiledb_config=azure_cred)
ds = tiledbvcf.Dataset(uri,
                       mode = "w",
                       cfg=config)
ds.create_dataset()
```
`RuntimeError: TileDB-VCF exception: Error setting TileDB config parameter; bad value 'vfs.azure.storage_sas_token=?sv=123456789==`

This could be due to the utils::split function, parsing multiple "=" that typically exist in Azure SAS & Azure Account Keys. 
See **utils.cc, lines 318-331**:

```
void set_tiledb_config(
    const std::vector<std::string>& params, tiledb_config_t* cfg) {
  tiledb_error_t* err;
  for (const auto& s : params) {
    auto kv = utils::split(s, '=');
    if (kv.size() != 2)
      throw std::runtime_error(
          "Error setting TileDB config parameter; bad value '" + s + "'");
    utils::trim(&kv[0]);
    utils::trim(&kv[1]);
    tiledb_config_set(cfg, kv[0].c_str(), kv[1].c_str(), &err);
    tiledb::impl::check_config_error(err);
  }
}
```

**Comment by gspowley** [comment]
Thank you @vstathias for the report and debug info. PR #605 should fix the issue.

**Comment by gspowley** [comment]
Yes, we're working on a 0.26.2 release, which will include the fix. It should be available within the next day or so.

**Comment by vstathias** [comment]
Perfect, thank you @gspowley!

**Comment by gspowley** [comment]
Please let us know if [0.26.2](https://github.com/TileDB-Inc/TileDB-VCF/releases/tag/0.26.2) resolved the issue.

**Comment by vstathias** [comment]
It works, thank you!
