### ISSUE TITLE
Wrong type hint for dataset python api 

### ISSUE THREAD

**Issue by lowmann15** [TileDB-Inc/TileDB-VCF#650]
## Issue Description
The python api for the dataset class contains a mode attribute which is type hinted as a boolean value, but will be handled as a string in the code.

## Expected Behavior
The correct type hint should be `str`

## Actual Behavior
The current type hint is `bool`

## Environment
tiledbvcf-py version `0.27.0`

**Comment by awenocur** [comment]
Thank you for bringing this to our attention. We'll add a fix to the next release.

**Comment by gspowley** [comment]
Resolved in #658.
