### ISSUE TITLE
Some questions about functionality

### ISSUE THREAD

**Issue by andreaswallberg** [TileDB-Inc/TileDB-VCF#707]
Dear developers and community,

I am looking at this technology with much interest and I have a couple of questions.

1. Using TileDB-VCF with TileDB Embedded, is there any built-in function to control user roles, credentials and permissions with regards to for example who can store and export data or is the tool simply inheriting the UNIX/POSIX system users and permissions?
2. Is the database able to store complex variants and haplotypes (for example, small or large indels, haplotype blocks) in addition to SNPs? How about phased vs. unphased variants?

Best regards,
Andreas

**Comment by andreaswallberg** [comment]
Thanks for the quick and clear reply!

1. Perhaps this is not the role of the open source development to support, but is there a migration path from TileDB Embedded to TileDB Cloud such that data can be uploaded without complicated interconvert or risk of data loss?
2. Moreover, in either TileDB Embedded or Cloud, is there a concept of versioning in the database so that users with different project roles may interact with different versions or segments of the database?

**Comment by leipzig** [comment]
1. The way TileDB Cloud works is that the data stays in your s3 buckets. You then "register" these existing TileDB-VCF stores in TileDB Cloud to allow you to compute on it, as well as manage its permissions within your group. So there is no conversion or data loss - the TileDB Open Source and TileDB Cloud use the exact same data in the same location.
<img width="567" alt="Screenshot 2024-04-26 at 9 49 41 AM" src="https://github.com/TileDB-Inc/TileDB-VCF/assets/147991/39181feb-5e9d-47be-afc5-fee66b0c8ad2">

2. There is versioning but access is not restricted to certain versions - if you have access to the array then you can time-travel back to any point, like git. Granular access to certain samples is on the roadmap. We'd love to understand your intended use so we can consider it in our plans.
