### ISSUE TITLE
ds.count(...) always reports 0 (samples not really ingested, but no error thrown)

### ISSUE THREAD

**Issue by ghost** [TileDB-Inc/TileDB-VCF#72]
First, is there a gitter or slack channel for tiledb? Pretty interesting project, and I'd like to get more plugged in with the community if there is one.

Second,

I have been able to ingest your test data just fine. For instance queries over all of the smalli.vcf.gz files behave as expected. However, I am not able to get a real cohort ingested properly. 

Specifically
```
import tiledbvcf

ds = tiledbvcf.TileDBVCFDataset('test-tiledbvcf', mode='w')
sample_names = [...]
sample_files = [...]
ds.ingest_samples(sample_files)

``` 

Seems to work fine. At least there's no errors, but the folder of the array has very little data in it.

```
$tree test-tiledbvcf/
test-tiledbvcf/
├── data
│   ├── __array_schema.tdb
│   ├── __lock.tdb
│   └── __meta
│       ├── __1586830166573_1586830166573_b44eea17956346ea998c06fec5f44d13
│       └── __1586830197336_1586830197336_8fe33e6c13b04b72bba2e232f32d22e3
├── metadata
│   ├── __tiledb_group.tdb
│   └── vcf_headers
│       ├── __1586830197325_1586830197325_ebdd203f6abb4b35ae8afdb6c0acb1b0
│       │   ├── __fragment_metadata.tdb
│       │   ├── header.tdb
│       │   └── header_var.tdb
│       ├── __array_schema.tdb
│       ├── __lock.tdb
│       └── __meta
└── __tiledb_group.tdb
```

```
$du -h ./test-tiledbvcf/
16K     ./test-tiledbvcf/metadata/vcf_headers/__1586830197325_1586830197325_ebdd203f6abb4b35ae8afdb6c0acb1b0
4.0K    ./test-tiledbvcf/metadata/vcf_headers/__meta
28K     ./test-tiledbvcf/metadata/vcf_headers
32K     ./test-tiledbvcf/metadata
12K     ./test-tiledbvcf/data/__meta
20K     ./test-tiledbvcf/data
56K     ./test-tiledbvcf/
```

Also, any count query such as 

```
dso.count(samples=sample_names, regions=[...])
```
returns 0.

The records of my cohort all look like:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  !REDACTED!
1       1       .       N       <NON_REF>       .       .       END=10003       GT:DP:GQ:MIN_DP:PL      0/0:0:0:0:0,0,0
1       10004   .       C       <NON_REF>       .       .       END=10006       GT:DP:GQ:MIN_DP:PL      0/0:27:9:25:0,9,135
1       10007   .       T       <NON_REF>       .       .       END=10007       GT:DP:GQ:MIN_DP:PL      0/0:29:0:29:0,0,653
1       10008   .       A       <NON_REF>       .       .       END=10008       GT:DP:GQ:MIN_DP:PL      0/0:30:15:30:0,15,225
```

And the header seems to have all of the necessary fields and seem the same as the test samples. 

Any ideas?

**Comment by aaronwolen** [comment]
Thanks for posting this. We haven't been able to reproduce this issue internally but would like to try and get to the bottom of it. If you're willing to share an anonymized subset of your data for debugging, please reach out to us at hello@tiledb.com.

**Comment by jamesthegiantpeach** [comment]
A bizarre thing about this: The gvcf files are outputs from sentieon's haplotyper algorithm, and they have tabix .tbi indices. When I DEFLATE the gvcf files and recompress and reindex, the ingestion starts. There's an error 

```
RuntimeError: TileDB-VCF exception: [TileDB::Writer] Error: Duplicate coordinates are not allowed
```
but it looks like that is a different issue. Seems like it has something to do with sentieon's compression. I'll try to get you a genome that was run with this tool in the next couple days.

On the need for deduped coordinates:

Something I thought was interesting, is that after recompressing and indexing all of these files, I had noticed that none of them will successfully ingest. They are all stopped on the above duplicate coordinates runtime error. Is it possible that the tool is recognizing multi-allelic sites as duplicated coordinates?

**Comment by stavrospapadopoulos** [comment]
The duplicate coordinates issue occurs because we use the `END` field as the second dimension in the 2D array, and naturally there may be multiplicities. In the upcoming TileDB core version we allow duplicates, so we are planning on doing so for TileDB-VCF by default as well. The new release is just a few weeks away, but we will try to push this to TileDB-VCF dev sooner. 

As a side note, there used to be technical reason why we store the `END` of a gVCF range instead of the start, but that reason cease to exist after the latest algorithmic changes. We plan to store `START` in newer versions of TileDB-VCF.

**Comment by jamesthegiantpeach** [comment]
You should be able to get duplicate coordinates even when storing the start coordinate of a variant. For example:

Imagine you have a SNP at (i,j) where there’s two different versions of that SNP. That is the site is multi-allelic. The record in the VCF file can store this as a single record with a list in the ALT column, or there will be two records with two different values in the ALT column. Those two records will have (i,j) as coordinates. 

Are you storing ALT as an attribute that is a list of strings? I have not spent enough time with the data model.

**Comment by stavrospapadopoulos** [comment]
Agreed on allowing duplicates even for the start coordinates.

Re: `ALT` field, we are currently storing it as a varchar attribute where the list of alleles is a simple CSV string: https://docs.tiledb.com/developer/tiledbvcf/advanced/data-model#attributes

**Comment by jamesthegiantpeach** [comment]
Got it. So it I would just have to make sure all multi-allelic sites are collapsed into a single record. 

With respect to the pipeline that produced the original error: If you would like to reproduce, then would you be ok with downloading a wgs gVCF from our public S3 bucket? I can just send you NA12878

**Comment by aaronwolen** [comment]
Downloading from S3 would be no problem. 👍
