### ISSUE TITLE
Broken doc link 

### ISSUE THREAD

**Issue by jamesthegiantpeach** [TileDB-Inc/TileDB-VCF#73]
The link from the [data model](https://docs.tiledb.com/developer/tiledbvcf/advanced/data-model) doc to  the (genomics use case)[https://docs.tiledb.com/main/ssrSpaces/spaces/main/use-cases/genomics] doc seems to be broken. 

![image](https://user-images.githubusercontent.com/52935149/79270624-54e68400-7e53-11ea-85f9-9901bbde9f6d.png)

**Comment by stavrospapadopoulos** [comment]
Fixed, thanks!
