### ISSUE TITLE
can not load bcf files from tutorial

### ISSUE THREAD

**Issue by bruno-ariano** [TileDB-Inc/TileDB-VCF#743]
when following the tutorial at the step ds.ingest_samples(sample_uris = batch1_uris) I get the error:

RuntimeError: TileDB-VCF exception: Cannot open VCF file; failed to load BCF index.

**Comment by leipzig** [comment]
hi @bruno-ariano I can't replicate the error (I assume you mean [this tutorial])(https://tiledb-inc.github.io/TileDB-VCF/examples/tutorial_tiledbvcf_basics.html)?

can you `print(batch1_uris)` just to make sure we are on the same page?

**Comment by bruno-ariano** [comment]
Hi @leipzig, below is the screenshot from the script I have run following the tutorial.

![image](https://github.com/TileDB-Inc/TileDB-VCF/assets/26384813/b3e4df02-808d-41f8-bd73-88d24ad1b296)


`print(batch1_uris)` give me the following output

['s3://tiledb-inc-demo-data/examples/notebooks/vcfs/1kgp3-chr1/HG00096.bcf', 's3://tiledb-inc-demo-data/examples/notebooks/vcfs/1kgp3-chr1/HG00097.bcf', 's3://tiledb-inc-demo-data/examples/notebooks/vcfs/1kgp3-chr1/HG00099.bcf', 's3://tiledb-inc-demo-data/examples/notebooks/vcfs/1kgp3-chr1/HG00100.bcf', 's3://tiledb-inc-demo-data/examples/notebooks/vcfs/1kgp3-chr1/HG00101.bcf']

**Comment by bruno-ariano** [comment]
Thanks @leipzig I think it was a problem with the region I had on my aws
