### ISSUE TITLE
Help understanding disk space usage

### ISSUE THREAD

**Issue by andreaswallberg** [TileDB-Inc/TileDB-VCF#785]
Dear @leipzig and developers,

I am testing TileDB-VCF on a SNP dataset derived from a SNP array. It is a combined VCF that spans 2,740 genotyped individuals and ~4,600 SNPs of a non-model species. MIssingness is low (on average 5% missing genotypes per individual).

I splitted the VCF with bcftools and loaded each VCF into TileDB using the store command and was surprised by the resulting size of the database.

I wonder how I can understand, and possibly control, disk space usage for this dataset when storing it in TileDB.

These are the file sizes:

- bgzipped combined vcf: 3.6M
- uncompressed combined vcf: 49M
- split bgzipped individual VCFs: 322M
- split uncompressed VCFs: 2.0G
- TileDB store: 3.1G

This is the size structure of the datastore as reported by `ncdu`:

```
    1,8 GiB [##########] /sample_stats                                                                                                               
  628,3 MiB [###       ] /data
  387,0 MiB [##        ] /allele_count
  285,3 MiB [#         ] /variant_stats
    7,6 MiB [          ] /metadata
   24,0 KiB [          ] /__group
    8,0 KiB [          ] /__meta
    0,0   B [          ]  __tiledb_group.tdb
```

It seems like I have inflated disk space usage 1000x compared the original compressed combined vcf and that I am using more space than individual uncompressed VCFs.

My guess is that there is meta data overhead in sample_stats that scales unfavorably for SNP datasets with many individuals but few SNPs, but perhaps I have also not configured compression correctly.

Can someone please advice on if and how I can optimize disk space usage in this scenario?

**Comment by leipzig** [comment]
Hey @andreaswallberg can you send us this VCF file? Our developer @gspowley has some ideas but we would need to see what the true cause of this size inflation is.

**Comment by andreaswallberg** [comment]
> Hey @andreaswallberg can you send us this VCF file? Our developer @gspowley has some ideas but we would need to see what the true cause of this size inflation is.

You have mail! Sorry for the delay.

**Comment by andreaswallberg** [comment]
Hi again!

The issue was a user error over here.

I stored the genotypes using the default sample batch size (`-e,--sample-batch-size UINT=10`). Switching it to a batch size larger than the sample size (n=2,740) solved the issue:

```
tiledbvcf store -u vcf.tdb -e 3000 -m 1024 -t 2 --log-level info $DIR/*.bcf
```
Yields a much more reasonable data store:

```
   20,5 MiB [##########] /data                                                                                                                                                                                             
    8,9 MiB [####      ] /variant_stats
    1,6 MiB [          ] /allele_count
  392,0 KiB [          ] /sample_stats
  260,0 KiB [          ] /metadata
   24,0 KiB [          ] /__group
    8,0 KiB [          ] /__meta
    0,0   B [          ]  __tiledb_group.tdb
```
    
Thanks for the help!
