### ISSUE TITLE
Deleting samples takes a very long time - are there optimizations or best practices?

### ISSUE THREAD

**Issue by jpcartailler** [TileDB-Inc/TileDB-VCF#791]
Greetings,

I have a database with about 1000 samples. The ingested data was GVCFs. We need to remove a number of samples, due to a loading mistake. 

The setup is:
TileDB-VCF version 0.35.0
TileDB version 2.26.1
htslib version 1.20

The database is consolidated and vacuumed. 

The delete command (note: sample names abridged)
```
tiledbvcf delete --uri ${DATABASE} --log-level debug --log-file delete.log --sample-names 1,2,3,4,5 --tiledb-config num_threads=50
```

After about 12 hours, it has completed about 1% of the contigs:
```
[2024-12-03 14:04:58.954] [tiledb-vcf] [Process: 708725] [Thread: 708725] [info] Initialized TileDB query with 1 start_pos ranges, 60 for contig HLA-A*02:53N (contig batch 37/3366, sample batch 1/1).
```

Hence, I am concerned about how long it will take for this to complete, especially once it hits the large contigs.

My questions are:
* Is this deletion rate expected? 
* Are there ways to speed it up?
* Is it best to pass multiple samples at once? Upper limit?
* Can it be parallelized and sample list chunked?

I appreciate any guidance and feedback, thank you for your time.

**Comment by leipzig** [comment]
Hi @jpcartailler. Thanks for reaching out. We don't get a lot of deletion questions so I apologize in advance.

- Is this deletion rate expected?

Basically yes. TileDB-VCF is not really optimized for deletion. Open source TileDB-VCF in particular is a means of guaranteeing access to TileDB-VCF datasets, forever.

There ingestion and query of VCF assets are parallelized in TileDB Cloud. Deletion is not a cloud-optimized task, though it could be.

- Are there ways to speed it up?

What is really holding this up the deletion is the 3366 contigs in the reference. All those unscaffolded contigs, decoys, and other weird things are problematic in this case. I wouldn't worry about large contigs per se. 

![contigs](https://assets.illumina.com/content/dam/illumina-marketing/images/genomics-research/articles/demystifying-reference-genome-dragen/dragen-Table2-squoosh.jpg)

- Is it best to pass multiple samples at once? Upper limit?

Not sure there is an upper limit but yes I think it is best to do multiple samples. There is probably a point at which is becomes preferable to reingest. What concerns me about deleting individual samples in serial is the recalculation of allele frequency statistics would be repeated.

- Can it be parallelized and sample list chunked?

We would be open to optimizing this in TileDB Cloud

**Comment by jpcartailler** [comment]
Hi @leipzig - thanks for the detailed response and thoughts, it was all very helpful. I appreciate your willingness to explore optimizations, but I don't think that is necessary for the time being. We will be more judicious in how we load in the future. Cheers!
